#!/bin/bash
# Date: 2024-12-03
# Description: This script gathers and reports workload, pod, and container statistics for each Kubernetes context.
# Author: Daniel Mandelblat
# Email: danielmande@gmail.com

contexts=$(kubectl config view -ojson | jq -r '.contexts[].name')

for context in $contexts
do
    kubectl cluster-info --context $context  &>/dev/null
	
    # Collect information
    sts=$(kubectl get sts -A --no-headers --context $context | wc -l)
    daemonsets=$(kubectl get sdaemonsets -A --no-headers --context $context | wc -l)
    deploys=$(kubectl get deploy -A --no-headers --context $context | wc -l)
    workloads=$((sts + daemonsets + deploys))
    pods=$(kubectl get pods -A --no-headers --context $context | wc -l)
    containers=$(kubectl get pods -A -ojson --context $context | jq -r '.items[].spec.containers' | jq 'length' | awk '{sum += $1} END {print sum}')

    echo  "========= $context report ========="
    echo "Workloads: ${workloads}"
    echo "Statefullsets: ${sts}"
    echo "Daemonsets: ${daemonsets}"
    echo "Deploymnets: ${deploys}"
    echo "Pods: ${pods}"
    echo "Containers: ${containers}"
done
